import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Header";
import About from "../components/About";
import Token from "../components/Token";
import Help from "../components/Help";
import PlayerToEarn from "../components/PlayerToEarn";
import RoadMap from "../components/RoadMap";
import Members from "../components/Members";
import Footer from "../components/Footer";
export default function Home() {
  return (
    <div className="bg-black h-screen overflow-x-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="">
        <Banner />

        <About />

        <Token />

        <Help />

        <PlayerToEarn />

        <RoadMap />

        <Members title="TEAM MEMBERS" />
        <Members Advisory title="ADVISORY" />

        <Footer />
      </main>
    </div>
  );
}
